#######################################################################################
# Book settings
title: "" # The title of the book. Will be placed in the left navbar.
logo: assets/logo.svg # A path to the book logo
author: the teamtomo.org contributors # The author of the book
email: ttomo@googlegroups.com
copyright: "2021" # Copyright year to be placed in the footer
only_build_toc_files: false

execute:
  execute_notebooks: cache

exclude_patterns: [README.md]

myst_enable_extensions: [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

html:
  favicon: assets/favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  html_css_files: ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"]
#  baseurl: https://jupyterbook.org/

repository:
  url: https://github.com/teamtomo/teamtomo.github.io
  branch: master
  path_to_book: .

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: ""
  colab_url: ""
  thebe: false

latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd
    mathjax3_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
    latex_elements:
        preamble: |
          \newcommand\N{\mathbb{N}}
          \newcommand\floor[1]{\lfloor#1\rfloor}
          \newcommand{\bmat}{\left[\begin{array}}
          \newcommand{\emat}{\end{array}\right]}
    language: en

  extra_extensions: [sphinx_inline_tabs]
